# -*- coding: utf-8 -*-
"""Sistema_Gestion_Pedagogica.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qt2XxOSDpYrpNLBMLIG-CmS-78fU7yiA
"""

!pip install fastapi uvicorn streamlit psycopg2-binary google-api-python-client google-auth-httplib2 google-auth-oauthlib requests pandas

# Carga de librerías principales
!pip install -q streamlit pyngrok psycopg2-binary google-api-python-client pandas requests

import pandas as pd
import datetime

print("✅ Entorno preparado exitosamente en Google Colab.")

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import pandas as pd
# import datetime
# 
# # Configuración de página
# st.set_page_config(page_title="Sistema Pedagógico I.E.", page_icon="📚", layout="wide")
# 
# st.markdown("""
#     <style>
#     .main-title { color: #1E3A8A; font-size: 28px; font-weight: bold; }
#     .stButton>button { background-color: #2563EB; color: white; border-radius: 6px; }
#     </style>
# """, unsafe_allow_html=True)
# 
# # Menú Lateral / Selección de Rol
# st.sidebar.image("https://cdn-icons-png.flaticon.com/512/3135/3135715.png", width=70)
# st.sidebar.title("I.E. Control Pedagógico")
# rol = st.sidebar.selectbox("Seleccionar Rol de Usuario:", ["Director", "Coordinador", "Docente"])
# 
# st.sidebar.divider()
# st.sidebar.caption("Sincronizado con Google Drive & PostgreSQL")
# 
# # -----------------------------------------------------------------------------
# # 1. VISTA DIRECTOR
# # -----------------------------------------------------------------------------
# if rol == "Director":
#     st.markdown("<p class='main-title'>📊 Dashboard Institucional - Dirección</p>", unsafe_allow_html=True)
#     st.caption("Visión general del estado del cumplimiento de la plana docente.")
# 
#     col1, col2, col3, col4 = st.columns(4)
#     col1.metric("Cumplimiento General", "87.5%", "🟢 Meta OK")
#     col2.metric("Documentos Entregados", "342 / 390", "🟢 87.6%")
#     col3.metric("Pendientes", "36", "-4 esta semana")
#     col4.metric("Observados", "12", "🔴 Corregir", delta_color="inverse")
# 
#     st.divider()
#     st.subheader("📋 Resumen por Coordinaciones")
# 
#     data_coordinaciones = {
#         "Coordinación": ["Matemática y Ciencias", "Letras y Comunicación", "Innovación y EPT", "Desarrollo Personal", "Primaria"],
#         "Docentes Asignados": [12, 15, 8, 7, 8],
#         "Entregados": [110, 125, 60, 47, 0],
#         "Pendientes": [4, 6, 2, 8, 16],
#         "Cumplimiento (%)": [96.4, 95.4, 96.7, 85.4, 0.0]
#     }
#     st.dataframe(pd.DataFrame(data_coordinaciones), use_container_width=True)
# 
# # -----------------------------------------------------------------------------
# # 2. VISTA COORDINADOR
# # -----------------------------------------------------------------------------
# elif rol == "Coordinador":
#     st.markdown("<p class='main-title'>🔍 Revisión Pedagógica - Coordinación</p>", unsafe_allow_html=True)
# 
#     st.selectbox("Seleccionar Docente a Cargo:", ["Prof. Juan Pérez (Matemática)", "Prof. María López (Ciencias)", "Prof. Carlos Quispe (EBR)"])
# 
#     st.subheader("Documentos Recibidos para Revisión")
# 
#     docs_data = {
#         "Fecha Subida": ["10/08/2026", "11/08/2026", "12/08/2026"],
#         "Documento": ["Programación Anual 2026", "Unidad 01 - Matemática", "Sesión 05 - 2do A"],
#         "Alcance": ["Área + Grado", "Por Grado", "Individual"],
#         "Estado Actual": ["🟢 APROBADO", "🔴 OBSERVADO", "🟡 EN REVISIÓN"]
#     }
#     st.table(pd.DataFrame(docs_data))
# 
#     st.divider()
#     st.subheader("✍️ Registrar Revisión u Observación")
#     with st.form("form_revision"):
#         doc_evaluar = st.selectbox("Seleccionar documento a revisar:", ["Sesión 05 - 2do A"])
#         accion = st.radio("Acción de Revisión:", ["APROBAR Y FIRMAR", "OBSERVAR Y SOLICITAR CORRECCIÓN"])
#         comentario = st.text_area("Observación o Criterio a mejorar:")
#         btn_revisar = st.form_submit_button("Guardar Revisión")
# 
#         if btn_revisar:
#             st.success(f"Revisión registrada con éxito. Estado: {accion}")
# 
# # -----------------------------------------------------------------------------
# # 3. VISTA DOCENTE (SUBIDA DE ARCHIVOS)
# # -----------------------------------------------------------------------------
# elif rol == "Docente":
#     st.markdown("<p class='main-title'>📤 Módulo de Carga - Prof. Juan Pérez</p>", unsafe_allow_html=True)
#     st.write("**Áreas Asignadas:** Matemática, Ciencia y Tecnología | **Semana Activa:** Semana 05")
# 
#     st.divider()
# 
#     with st.form("form_docente"):
#         st.subheader("Subir Documento Técnico-Pedagógico")
# 
#         tipo_doc = st.selectbox("Tipo de Documento:", ["Programación Anual", "Unidad de Aprendizaje", "Sesión de Aprendizaje"])
#         alcance = st.selectbox("Alcance del Documento:", ["Individual (Solo mi sección)", "Por Área y Grado (Compartido con otros docentes)", "Por Sección"])
# 
#         archivo = st.file_uploader("Cargar Archivo (PDF, DOCX, XLSX):", type=["pdf", "docx", "xlsx"])
#         notas = st.text_area("Comentarios para la coordinación:")
# 
#         subir = st.form_submit_button("Subir Documento")
# 
#         if subir:
#             if archivo is not None:
#                 st.success(f"✅ Archivo **{archivo.name}** procesado exitosamente.")
#                 st.info("🔄 Sincronizando con Google Drive y asignando identificadores...")
#             else:
#                 st.error("⚠️ Selecciona un archivo antes de enviar.")

# 1. Obtener IP pública requerida por LocalTunnel como contraseña
!curl https://loca.lt/mytunnelpassword

# 2. Levantar la interfaz web en segundo plano
!streamlit run app.py & npx localtunnel --port 8501

from pyngrok import ngrok
import os

# Cerrar conexiones previas si existen
ngrok.kill()

# Abrir túnel público al puerto de Streamlit (8501)
public_url = ngrok.connect(8501)
print(f"🚀 ¡TU INTERFAZ WEB ESTÁ LISTA EN ESTE ENLACE! 👉 {public_url}")

# Ejecutar Streamlit en segundo plano
!streamlit run app.py &

# 1. Matar procesos anteriores
!pkill -f streamlit

# 2. Iniciar Streamlit en segundo plano
import subprocess
subprocess.Popen(["streamlit", "run", "app.py", "--server.port", "8501"])

# 3. Crear enlace directo público sin registros ni contraseñas
import time
time.sleep(3) # Esperar a que active Streamlit

print("⏳ Generando tu enlace de acceso...")
!ssh -o StrictHostKeyChecking=no -R 80:localhost:8501 serveo.net

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import pandas as pd
# import os
# 
# # 📍 Lista de posibles rutas para 'sistema_carpeta-pedagógica' en Colab/Drive
# RUTAS_POSIBLES = [
#     "/content/drive/MyDrive/sistema_carpeta-pedagógica",
#     "/content/drive/MyDrive/sistema_carpeta-pedagogica",
#     "/content/drive/Shareddrives/sistema_carpeta-pedagógica",
#     "/content/drive/MyDrive/Carpeta Pedagógica 2026"
# ]
# 
# def buscar_ruta_valida():
#     for r in RUTAS_POSIBLES:
#         if os.path.exists(r):
#             return r
#     return None
# 
# CARPETA_RAIZ = buscar_ruta_valida()
# 
# def obtener_estructura_drive(ruta_base):
#     """
#     Recorre las carpetas en Google Drive y mapea dinámicamente:
#     Coordinaciones -> Áreas -> Docentes
#     """
#     estructura = {}
#     if ruta_base and os.path.exists(ruta_base):
#         for coord in sorted(os.listdir(ruta_base)):
#             ruta_coord = os.path.join(ruta_base, coord)
#             if os.path.isdir(ruta_coord) and not coord.startswith('.'):
#                 estructura[coord] = {}
#                 for area in sorted(os.listdir(ruta_coord)):
#                     ruta_area = os.path.join(ruta_coord, area)
#                     if os.path.isdir(ruta_area) and not area.startswith('.'):
#                         docentes = [
#                             d for d in sorted(os.listdir(ruta_area))
#                             if os.path.isdir(os.path.join(ruta_area, d)) and not d.startswith('.')
#                         ]
#                         estructura[coord][area] = docentes
#     return estructura
# 
# ESTRUCTURA = obtener_estructura_drive(CARPETA_RAIZ)
# 
# # Configuración de la interfaz
# st.set_page_config(page_title="Sistema Pedagógico I.E.", page_icon="📚", layout="wide")
# 
# st.sidebar.title("🏛️ I.E. Control Pedagógico")
# rol = st.sidebar.selectbox("Seleccionar Rol:", ["Docente", "Coordinador", "Director"])
# st.sidebar.divider()
# 
# # -----------------------------------------------------------------------------
# # 👨‍🏫 VISTA DOCENTE
# # -----------------------------------------------------------------------------
# if rol == "Docente":
#     st.title("👨‍🏫 Módulo de Carga Pedagógica")
#     st.caption("Almacenamiento directo en Google Drive: `sistema_carpeta-pedagógica`")
# 
#     if not CARPETA_RAIZ:
#         st.error("⚠️ No se encontró la carpeta 'sistema_carpeta-pedagógica' en tu Google Drive. Asegúrate de tener 'drive.mount('/content/drive')' ejecutado y la carpeta visible en Mi Unidad.")
#     elif not ESTRUCTURA:
#         st.warning("📂 Se encontró la carpeta raíz 'sistema_carpeta-pedagógica', pero aún no tiene subcarpetas creadas (Coordinaciones / Áreas / Docentes).")
#     else:
#         col_c, col_a, col_d = st.columns(3)
# 
#         with col_c:
#             coordinacion_sel = st.selectbox("1. Coordinación:", list(ESTRUCTURA.keys()))
# 
#         areas_disponibles = list(ESTRUCTURA[coordinacion_sel].keys()) if coordinacion_sel else []
#         with col_a:
#             area_sel = st.selectbox("2. Área Pedagógica:", areas_disponibles)
# 
#         docentes_disponibles = ESTRUCTURA[coordinacion_sel][area_sel] if (coordinacion_sel and area_sel) else []
#         with col_d:
#             docente_sel = st.selectbox("3. Docente:", docentes_disponibles)
# 
#         st.divider()
# 
#         with st.form("form_subida_jerarquica"):
#             st.subheader(f"📤 Cargar Archivo para: {docente_sel}")
# 
#             tipo_doc = st.selectbox("Tipo de Documento:", ["PROGRAMACION_ANUAL", "UNIDAD_DE_APRENDIZAJE", "SESION_DE_APRENDIZAJE", "INSTRUMENTO_EVALUACION"])
#             periodo = st.selectbox("Periodo / Bimestre:", ["Bimestre I", "Bimestre II", "Bimestre III", "Bimestre IV"])
# 
#             archivo = st.file_uploader("Seleccionar Archivo (PDF, DOCX, XLSX):", type=["pdf", "docx", "xlsx"])
#             observacion = st.text_area("Comentarios para la Coordinación:")
# 
#             btn_subir = st.form_submit_button("🚀 Subir a Carpeta de Google Drive")
# 
#             if btn_subir:
#                 if archivo is not None:
#                     ruta_destino = os.path.join(CARPETA_RAIZ, coordinacion_sel, area_sel, docente_sel)
#                     nombre_archivo = f"{periodo.replace(' ','_')}_{tipo_doc}_{archivo.name}"
#                     ruta_completa = os.path.join(ruta_destino, nombre_archivo)
# 
#                     with open(ruta_completa, "wb") as f:
#                         f.write(archivo.getbuffer())
# 
#                     st.success("✅ ¡El documento se guardó correctamente en Google Drive!")
#                     st.info(f"📍 **Ubicación:** `sistema_carpeta-pedagógica / {coordinacion_sel} / {area_sel} / {docente_sel} / {nombre_archivo}`")
#                 else:
#                     st.error("⚠️ Por favor adjunta un archivo antes de presionar el botón.")
# 
# # -----------------------------------------------------------------------------
# # 🔍 VISTA COORDINADOR
# # -----------------------------------------------------------------------------
# elif rol == "Coordinador":
#     st.title("🔍 Módulo de Revisión - Coordinación")
# 
#     if ESTRUCTURA:
#         coord_rev = st.selectbox("Seleccionar Coordinación:", list(ESTRUCTURA.keys()))
#         area_rev = st.selectbox("Seleccionar Área:", list(ESTRUCTURA[coord_rev].keys()))
# 
#         st.divider()
#         st.subheader(f"📁 Estado Documental: {area_rev}")
# 
#         docentes_area = ESTRUCTURA[coord_rev][area_rev]
# 
#         for doc in docentes_area:
#             ruta_doc = os.path.join(CARPETA_RAIZ, coord_rev, area_rev, doc)
#             archivos = [a for a in os.listdir(ruta_doc) if not a.startswith('.')] if os.path.exists(ruta_doc) else []
# 
#             with st.expander(f"👨‍🏫 {doc} ({len(archivos)} archivos cargados)"):
#                 if archivos:
#                     for a in archivos:
#                         st.write(f"📄 {a}")
#                 else:
#                     st.caption("Aún no registra documentos en su carpeta.")
# 
# # -----------------------------------------------------------------------------
# # 📊 VISTA DIRECTOR
# # -----------------------------------------------------------------------------
# else:
#     st.title("📊 Resumen Consolidado - Dirección")
# 
#     if ESTRUCTURA:
#         resumen = []
#         for c, areas in ESTRUCTURA.items():
#             for a, docentes in areas.items():
#                 total_docs = 0
#                 for d in docentes:
#                     r = os.path.join(CARPETA_RAIZ, c, a, d)
#                     if os.path.exists(r):
#                         total_docs += len([f for f in os.listdir(r) if not f.startswith('.')])
# 
#                 resumen.append({
#                     "Coordinación": c,
#                     "Área": a,
#                     "Docentes Registrados": len(docentes),
#                     "Archivos Subidos": total_docs
#                 })
# 
#         st.dataframe(pd.DataFrame(resumen), use_container_width=True)

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import pandas as pd
# import os
# from google.colab import drive
# 
# # 1. Montar Google Drive si estamos en Colab
# DRIVE_FOLDER = "/content/drive/MyDrive/SISTEMA_PEDAGOGICO_DOCS"
# 
# def init_drive():
#     try:
#         if not os.path.exists('/content/drive'):
#             drive.mount('/content/drive', force_remount=True)
#         os.makedirs(DRIVE_FOLDER, exist_ok=True)
#         return True
#     except Exception as e:
#         return False
# 
# # Configuración de página
# st.set_page_config(page_title="Sistema Pedagógico I.E.", page_icon="📚", layout="wide")
# 
# # Sidebar
# st.sidebar.image("https://cdn-icons-png.flaticon.com/512/3135/3135715.png", width=70)
# st.sidebar.title("I.E. Control Pedagógico")
# rol = st.sidebar.selectbox("Seleccionar Rol de Usuario:", ["Docente", "Director", "Coordinador"])
# st.sidebar.divider()
# 
# # -----------------------------------------------------------------------------
# # VISTA DOCENTE (CON CONEXIÓN REAL A DRIVE)
# # -----------------------------------------------------------------------------
# if rol == "Docente":
#     st.title("👨‍🏫 Módulo de Carga - Prof. Juan Pérez")
#     st.write("**Áreas Asignadas:** Matemática, Ciencia y Tecnología | **Semana Activa:** Semana 05")
#     st.divider()
# 
#     with st.form("form_docente"):
#         st.subheader("📤 Subir Documento Técnico-Pedagógico")
# 
#         tipo_doc = st.selectbox("Tipo de Documento:", ["Programación Anual", "Unidad de Aprendizaje", "Sesión de Aprendizaje"])
#         area_grado = st.selectbox("Asignación:", ["Matemática - 2° Sec A", "Ciencia y Tech - 1° Sec A"])
#         alcance = st.radio("Alcance del Documento:", ["Individual", "Por Área y Grado (Compartido)", "Por Sección"])
# 
#         archivo = st.file_uploader("Seleccionar archivo (PDF, DOCX, XLSX):", type=["pdf", "docx", "xlsx"])
#         notas = st.text_area("Comentarios para la coordinación:")
# 
#         subir = st.form_submit_button("Guardar y Subir a Google Drive")
# 
#         if subir:
#             if archivo is not None:
#                 with st.spinner("Conectando con Google Drive y guardando archivo..."):
#                     if init_drive():
#                         # Normalizar nombre de archivo estandarizado
#                         nombre_limpio = f"2026_{tipo_doc.upper().replace(' ','_')}_{area_grado.replace(' ','_')}_{archivo.name}"
#                         ruta_destino = os.path.join(DRIVE_FOLDER, nombre_limpio)
# 
#                         # Guardar el archivo en Google Drive
#                         with open(ruta_destino, "wb") as f:
#                             f.write(archivo.getbuffer())
# 
#                         st.success(f"✅ ¡Archivo subido con éxito a Google Drive!")
#                         st.info(f"📁 **Ubicación:** `Mi Unidad / SISTEMA_PEDAGOGICO_DOCS / {nombre_limpio}`")
#                     else:
#                         st.error("⚠️ No se pudo autorizar el acceso a Google Drive.")
#             else:
#                 st.error("⚠️ Selecciona un archivo antes de enviar.")
# 
# # -----------------------------------------------------------------------------
# # VISTA DIRECTOR
# # -----------------------------------------------------------------------------
# elif rol == "Director":
#     st.title("📊 Dashboard Institucional - Dirección")
#     col1, col2, col3, col4 = st.columns(4)
#     col1.metric("Cumplimiento", "87.5%", "🟢 OK")
#     col2.metric("Entregados", "342 / 390", "🟢 87.6%")
#     col3.metric("Pendientes", "36", "-4")
#     col4.metric("Observados", "12", "🔴 Corregir", delta_color="inverse")
# 
#     st.divider()
#     st.subheader("📋 Resumen por Coordinaciones")
#     data_coordinaciones = {
#         "Coordinación": ["Matemática y Ciencias", "Letras y Comunicación", "Innovación y EPT"],
#         "Docentes": [12, 15, 8],
#         "Entregados": [110, 125, 60],
#         "Pendientes": [4, 6, 2],
#         "Cumplimiento (%)": [96.4, 95.4, 96.7]
#     }
#     st.dataframe(pd.DataFrame(data_coordinaciones), use_container_width=True)
# 
# # -----------------------------------------------------------------------------
# # VISTA COORDINADOR
# # -----------------------------------------------------------------------------
# elif rol == "Coordinador":
#     st.title("🔍 Revisión Pedagógica - Coordinación")
#     st.selectbox("Seleccionar Docente:", ["Prof. Juan Pérez", "Prof. María López"])
# 
#     st.subheader("Archivos Almacenados en Drive")
#     if os.path.exists(DRIVE_FOLDER):
#         archivos_drive = os.listdir(DRIVE_FOLDER)
#         if archivos_drive:
#             st.write(pd.DataFrame({"Archivos en Google Drive": archivos_drive}))
#         else:
#             st.info("Aún no hay archivos guardados en la carpeta de Drive.")
#     else:
#         st.info("La carpeta de Google Drive se creará al subir el primer documento.")

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import pandas as pd
# import os
# 
# # 📍 Ruta exacta apuntando a tu carpeta de Google Drive
# CARPETA_RAIZ = "/content/drive/MyDrive/carpeta pedagógica 2026"
# 
# def obtener_estructura_drive(ruta_base):
#     """
#     Recorre las carpetas en Google Drive y mapea dinámicamente:
#     Coordinaciones -> Áreas -> Docentes
#     """
#     estructura = {}
#     if not os.path.exists(ruta_base):
#         # Intento secundario por si los espacios o mayúsculas varían en Drive
#         posibles_rutas = [
#             "/content/drive/MyDrive/carpeta pedagógica 2026",
#             "/content/drive/MyDrive/Carpeta pedagógica 2026",
#             "/content/drive/MyDrive/Carpeta Pedagógica 2026"
#         ]
#         for r in posibles_rutas:
#             if os.path.exists(r):
#                 ruta_base = r
#                 break
# 
#     if os.path.exists(ruta_base):
#         for coord in sorted(os.listdir(ruta_base)):
#             ruta_coord = os.path.join(ruta_base, coord)
#             if os.path.isdir(ruta_coord) and not coord.startswith('.'):
#                 estructura[coord] = {}
#                 for area in sorted(os.listdir(ruta_coord)):
#                     ruta_area = os.path.join(ruta_coord, area)
#                     if os.path.isdir(ruta_area) and not area.startswith('.'):
#                         docentes = [
#                             d for d in sorted(os.listdir(ruta_area))
#                             if os.path.isdir(os.path.join(ruta_area, d)) and not d.startswith('.')
#                         ]
#                         estructura[coord][area] = docentes
#     return estructura, ruta_base
# 
# # Escanear la estructura real
# ESTRUCTURA, RUTA_CONFIRMADA = obtener_estructura_drive(CARPETA_RAIZ)
# 
# # Configuración de Streamlit
# st.set_page_config(page_title="Sistema Pedagógico I.E.", page_icon="📚", layout="wide")
# 
# # Sidebar
# st.sidebar.title("🏛️ I.E. Control Pedagógico")
# rol = st.sidebar.selectbox("Seleccionar Rol:", ["Docente", "Coordinador", "Director"])
# st.sidebar.divider()
# 
# # -----------------------------------------------------------------------------
# # 👨‍🏫 VISTA DOCENTE: SELECCIÓN DINÁMICA DE CARPETAS DE DRIVE
# # -----------------------------------------------------------------------------
# if rol == "Docente":
#     st.title("👨‍🏫 Módulo de Carga Pedagógica")
#     st.caption("Los archivos se guardan directamente en tu carpeta de Google Drive.")
# 
#     if not ESTRUCTURA:
#         st.error(f"⚠️ No se pudo encontrar la carpeta en Google Drive. Verifica que la carpeta 'carpeta pedagógica 2026' esté visible en 'Mi Unidad'.")
#     else:
#         # Desplegables en cascada según la estructura de tu Drive
#         col_c, col_a, col_d = st.columns(3)
# 
#         with col_c:
#             coordinacion_sel = st.selectbox("1. Coordinación:", list(ESTRUCTURA.keys()))
# 
#         areas_disponibles = list(ESTRUCTURA[coordinacion_sel].keys()) if coordinacion_sel else []
#         with col_a:
#             area_sel = st.selectbox("2. Área Pedagógica:", areas_disponibles)
# 
#         docentes_disponibles = ESTRUCTURA[coordinacion_sel][area_sel] if (coordinacion_sel and area_sel) else []
#         with col_d:
#             docente_sel = st.selectbox("3. Docente:", docentes_disponibles)
# 
#         st.divider()
# 
#         # Formulario de Subida
#         with st.form("form_subida_jerarquica"):
#             st.subheader(f"📤 Cargar Archivo para: {docente_sel}")
# 
#             tipo_doc = st.selectbox("Tipo de Documento:", ["PROGRAMACION_ANUAL", "UNIDAD_DE_APRENDIZAJE", "SESION_DE_APRENDIZAJE", "INSTRUMENTO_EVALUACION"])
#             periodo = st.selectbox("Periodo / Bimestre:", ["Bimestre I", "Bimestre II", "Bimestre III", "Bimestre IV"])
# 
#             archivo = st.file_uploader("Seleccionar Archivo (PDF, DOCX, XLSX):", type=["pdf", "docx", "xlsx"])
#             observacion = st.text_area("Comentarios para la Coordinación:")
# 
#             btn_subir = st.form_submit_button("🚀 Subir a Carpeta de Google Drive")
# 
#             if btn_subir:
#                 if archivo is not None:
#                     # Ruta física hacia la carpeta individual del docente en Google Drive
#                     ruta_destino = os.path.join(RUTA_CONFIRMADA, coordinacion_sel, area_sel, docente_sel)
# 
#                     # Formatear el nombre del archivo
#                     nombre_archivo = f"{periodo.replace(' ','_')}_{tipo_doc}_{archivo.name}"
#                     ruta_completa = os.path.join(ruta_destino, nombre_archivo)
# 
#                     # Guardar archivo directamente en Drive
#                     with open(ruta_completa, "wb") as f:
#                         f.write(archivo.getbuffer())
# 
#                     st.success("✅ ¡El documento se guardó correctamente en Google Drive!")
#                     st.info(f"📍 **Ubicación:** `carpeta pedagógica 2026 / {coordinacion_sel} / {area_sel} / {docente_sel} / {nombre_archivo}`")
#                 else:
#                     st.error("⚠️ Por favor adjunta un archivo antes de presionar el botón.")
# 
# # -----------------------------------------------------------------------------
# # 🔍 VISTA COORDINADOR: VER ARCHIVOS DE SU ÁREA EN TIEMPO REAL
# # -----------------------------------------------------------------------------
# elif rol == "Coordinador":
#     st.title("🔍 Módulo de Revisión - Coordinación")
# 
#     if ESTRUCTURA:
#         coord_rev = st.selectbox("Seleccionar Coordinación:", list(ESTRUCTURA.keys()))
#         area_rev = st.selectbox("Seleccionar Área:", list(ESTRUCTURA[coord_rev].keys()))
# 
#         st.divider()
#         st.subheader(f"📁 Estado Documental: {area_rev}")
# 
#         docentes_area = ESTRUCTURA[coord_rev][area_rev]
# 
#         for doc in docentes_area:
#             ruta_doc = os.path.join(RUTA_CONFIRMADA, coord_rev, area_rev, doc)
#             archivos = [a for a in os.listdir(ruta_doc) if not a.startswith('.')] if os.path.exists(ruta_doc) else []
# 
#             with st.expander(f"👨‍🏫 {doc} ({len(archivos)} archivos cargados)"):
#                 if archivos:
#                     for a in archivos:
#                         st.write(f"📄 {a}")
#                 else:
#                     st.caption("Aún no registra documentos en su carpeta de Google Drive.")
# 
# # -----------------------------------------------------------------------------
# # 📊 VISTA DIRECTOR: CONSOLIDADO GENERAL DE TODAS LAS CARPETAS
# # -----------------------------------------------------------------------------
# else:
#     st.title("📊 Resumen Consolidado - Dirección")
# 
#     if ESTRUCTURA:
#         resumen = []
#         for c, areas in ESTRUCTURA.items():
#             for a, docentes in areas.items():
#                 total_docs = 0
#                 for d in docentes:
#                     r = os.path.join(RUTA_CONFIRMADA, c, a, d)
#                     if os.path.exists(r):
#                         total_docs += len([f for f in os.listdir(r) if not f.startswith('.')])
# 
#                 resumen.append({
#                     "Coordinación": c,
#                     "Área": a,
#                     "Docentes Registrados": len(docentes),
#                     "Archivos Subidos": total_docs
#                 })
# 
#         st.dataframe(pd.DataFrame(resumen), use_container_width=True)